name: fal pytest

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "projects/fal/**"
      - ".github/**"
      - "!.github/workflows/*adapter*"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        dbt: ["1.0.*", "1.1.*", "1.2.*"]
        exclude:
          # Only DBT 1.1+ supports Python 3.10 (officially)
          - python: 3.10
            dbt: "1.0.*"

    # Run only the latest commit pushed to PR
    concurrency:
      group: "${{ github.ref }}-${{ github.workflow }}-${{ matrix.dbt }}-${{ matrix.python }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup local fal
        uses: ./.github/actions/setup-local-fal
        with:
          python: ${{ matrix.python }}
          dbt: ${{ matrix.dbt }}
          adapter: postgres

      - name: Start Docker database
        working-directory: tests
        run: docker-compose up -d

      - name: Setup pytest
        run: pip install pytest pytest-mock mock black

      - name: Run dbt
        run: dbt run --profiles-dir projects/fal/tests/mock/mockProfile/ --project-dir projects/fal/tests/mock

      - name: Run tests
        env:
          FAL_STATS_ENABLED: false
        run: pytest tests -s
