name: fal pytest

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "projects/fal/**"
      - ".github/**"
      - "!.github/workflows/*adapter*"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.7"
          # - "3.8"
          # - "3.9"
          - "3.10"
          - "3.11"
        dbt:
          - "1.5.*"

    # Run only the latest commit pushed to PR
    concurrency:
      group: "${{ github.ref }}-${{ github.workflow }}-${{ matrix.dbt }}-${{ matrix.python }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup local fal
        uses: ./.github/actions/setup-local-fal
        with:
          python: ${{ matrix.python }}
          dbt: ${{ matrix.dbt }}
          adapter: postgres

      - name: Start Docker database
        working-directory: projects/fal/tests
        run: docker-compose up -d

      - name: Setup pytest
        run: pip install pytest pytest-mock mock black

      - name: Run dbt
        working-directory: projects/fal
        run: dbt run --profiles-dir tests/mock/mockProfile/ --project-dir tests/mock

      - name: Run tests
        working-directory: projects/fal
        env:
          FAL_STATS_ENABLED: false
          DBT_TARGET_PATH: mockTarget
        run: pytest tests -s
